name: Feature Request
description: Suggest a new feature or enhancement for the Goose Hints Builder
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide details about your idea.

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New preference category
        - User interface improvement
        - Platform compatibility
        - Cloud storage integration
        - Goose integration enhancement
        - Performance improvement
        - Documentation improvement
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my workflow
        - Critical - Blocking my usage
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What's the current limitation?
      placeholder: Describe the problem or limitation you're experiencing.
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe your ideal solution to this problem.
      placeholder: What would you like to see implemented?
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe how you would use this feature in your workflow.
      placeholder: Walk us through a typical scenario where this feature would be helpful.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Describe any alternative approaches you've thought about.

  - type: dropdown
    id: edition-impact
    attributes:
      label: Edition Impact
      description: Which edition(s) would this feature affect?
      options:
        - Simple Edition only
        - Comprehensive Edition only
        - Both editions
        - New edition/mode
        - Infrastructure/shared code
    validations:
      required: true

  - type: textarea
    id: implementation-ideas
    attributes:
      label: Implementation Ideas
      description: If you have ideas about how this could be implemented, please share them.
      placeholder: Any technical thoughts or suggestions for implementation?

  - type: checkboxes
    id: compatibility
    attributes:
      label: Compatibility Considerations
      description: Please consider the following aspects
      options:
        - label: This feature should work across all platforms (Windows, macOS, Linux)
        - label: This feature should maintain backward compatibility
        - label: This feature should integrate well with Goose's memory system
        - label: This feature should be optional/configurable

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to make sure this is not a duplicate
          required: true
        - label: I have considered the impact on both Simple and Comprehensive editions
          required: true
        - label: I have provided a clear use case for this feature
          required: true
